# https://github.com/geerlingguy/ansible-role-mas
# https://github.com/geerlingguy/ansible-role-mas/blob/master/tasks/main.yml
- name: Mac App Store
  hosts: all
  tags: mas
  vars:
    - mas_email: mpcannabrava@gmail.com
  tasks:
    - homebrew: state=present name=mas
    - name: verify MAS logged in status
      shell: "mas account"
      register: mas_account_result
      failed_when: mas_account_result.rc > 1
      changed_when: false

    - command: mas list
      register: mas_list
      check_mode: no
      changed_when: false

    - name: install MAS apps
      tags: mas
      command: mas install "{{ item.id|default(item) }}"
      when: (item.id | default(item) | string) not in mas_list.stdout
      with_items:
        - { id: 409183694,  name: "Keynote" }
        - { id: 803453959,  name: "Slack" }
        - { id: 497799835,  name: "Xcode" }
