---
- name: NodeJS Development Environment
  hosts: all
  tags: node
  vars:
    global_modules:
      - github-email
      - serve

  tasks:
    - name: install NodeJS platform
      homebrew: name=node state=present
      check_mode: false

    - name: install NVM
      homebrew: name=nvm state=present

    - name: install NodeJS global dev tools
      npm: state=present name={{ item }} global=yes
      with_items: "{{ global_modules }}"
