---
- name: Rust Development Environment
  hosts: all
  tags: rust

  tasks:
    - name: install homebrew stub for rustup
      homebrew: name=rustup-init state=present

    - name: use rustup-init to bootstrap rustup (& stable rust automaticaly)
      command: rustup-init -y --no-modify-path
      args:
        creates: ~/.cargo/bin/rustc
